name: Test and Build

on:
  push:
    branches:
      - main
    paths:
      - '**/*'

jobs:
  build:
    runs-on: node1

    steps:
    #Setting up environment
      - name: Checkout code
        uses: actions/checkout@v2

  Setup Python:
    runs-on: node1
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

  Docker Setup:
    runs-on: node1
    steps:
      - name: Docker Setup
        uses: docker/setup-buildx-action@v2

  Install dependencies:
    runs-on: node1
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

  Run Linting tests:
    runs-on: node1
    steps:

      # Test the Code
      - name: Run Linting tests
        run: |
          flake8 --ignore=E501,F401 .
      
      - name: Docker Credentials
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
